// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdaxwzwW-2m3tqJY7mUFogrRR96HWrQCY',
    appId: '1:128633944154:web:f06e7e198d26b95f9e0063',
    messagingSenderId: '128633944154',
    projectId: 'spotivibes-bad61',
    authDomain: 'spotivibes-bad61.firebaseapp.com',
    databaseURL: 'https://spotivibes-bad61-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spotivibes-bad61.appspot.com',
    measurementId: 'G-ZE69N25SE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPMQdDCxUx_e3JEoCLOVObMwX4VPwpEUA',
    appId: '1:128633944154:android:c74a5ac00155163e9e0063',
    messagingSenderId: '128633944154',
    projectId: 'spotivibes-bad61',
    databaseURL: 'https://spotivibes-bad61-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spotivibes-bad61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbQtiNxOiVkxEYvclsSBouZBgfGHknq84',
    appId: '1:128633944154:ios:25bb2d0783f7f07a9e0063',
    messagingSenderId: '128633944154',
    projectId: 'spotivibes-bad61',
    databaseURL: 'https://spotivibes-bad61-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spotivibes-bad61.appspot.com',
    iosClientId: '128633944154-s31sjr9vahaad3i9pagnutgvbltchalb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbQtiNxOiVkxEYvclsSBouZBgfGHknq84',
    appId: '1:128633944154:ios:25bb2d0783f7f07a9e0063',
    messagingSenderId: '128633944154',
    projectId: 'spotivibes-bad61',
    databaseURL: 'https://spotivibes-bad61-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'spotivibes-bad61.appspot.com',
    iosClientId: '128633944154-s31sjr9vahaad3i9pagnutgvbltchalb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
